import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

/**
 * API برای تولید گزارش PDF از نتیجه تست
 * GET /api/report/[testId]
 */
export async function GET(
  req: NextRequest,
  { params }: { params: { testId: string } }
) {
  try {
    const session = await getServerSession(authOptions);
    
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { testId } = params;

    // دریافت نتیجه تست
    const testResult = await prisma.testResult.findUnique({
      where: { id: testId },
      include: {
        user: {
          select: {
            name: true,
            email: true
          }
        }
      }
    });

    if (!testResult) {
      return NextResponse.json({ error: 'Test result not found' }, { status: 404 });
    }

    // بررسی دسترسی (فقط خود کاربر یا درمانگر/ادمین)
    if (
      testResult.userId !== session.user.id &&
      session.user.role !== 'therapist' &&
      session.user.role !== 'admin'
    ) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    // ایجاد PDF
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]); // A4 size
    const { width, height } = page.getSize();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let yPosition = height - 50;

    // هدر
    page.drawText('Testology - Psychology Test Report', {
      x: 50,
      y: yPosition,
      size: 24,
      font: boldFont,
      color: rgb(0.2, 0.2, 0.8),
    });

    yPosition -= 30;

    // خط جداکننده
    page.drawLine({
      start: { x: 50, y: yPosition },
      end: { x: width - 50, y: yPosition },
      thickness: 2,
      color: rgb(0.2, 0.2, 0.8),
    });

    yPosition -= 40;

    // اطلاعات تست
    page.drawText('Test Information', {
      x: 50,
      y: yPosition,
      size: 16,
      font: boldFont,
      color: rgb(0.1, 0.1, 0.1),
    });

    yPosition -= 25;

    const testInfo = [
      `Test Name: ${testResult.testName || testResult.testSlug}`,
      `Test ID: ${testResult.id}`,
      `Date: ${new Date(testResult.createdAt).toLocaleDateString('en-US')}`,
      `User: ${testResult.user?.name || 'N/A'}`,
      `Score: ${testResult.score !== null ? testResult.score.toFixed(2) : 'N/A'}`,
      `Severity: ${testResult.severity || 'N/A'}`,
    ];

    testInfo.forEach((line) => {
      page.drawText(line, {
        x: 70,
        y: yPosition,
        size: 12,
        font,
        color: rgb(0.2, 0.2, 0.2),
      });
      yPosition -= 20;
    });

    yPosition -= 20;

    // تحلیل و نتایج
    page.drawText('Analysis & Interpretation', {
      x: 50,
      y: yPosition,
      size: 16,
      font: boldFont,
      color: rgb(0.1, 0.1, 0.1),
    });

    yPosition -= 25;

    // تقسیم متن تحلیل به خطوط
    const interpretation = testResult.interpretation || testResult.resultText || 'No interpretation available';
    const lines = wrapText(interpretation, 75);

    lines.forEach((line) => {
      if (yPosition < 100) {
        // صفحه جدید
        const newPage = pdfDoc.addPage([595, 842]);
        yPosition = height - 50;
        newPage.drawText(line, {
          x: 70,
          y: yPosition,
          size: 11,
          font,
          color: rgb(0.2, 0.2, 0.2),
        });
      } else {
        page.drawText(line, {
          x: 70,
          y: yPosition,
          size: 11,
          font,
          color: rgb(0.2, 0.2, 0.2),
        });
      }
      yPosition -= 18;
    });

    yPosition -= 30;

    // توصیه‌ها
    if (yPosition > 150) {
      page.drawText('Recommendations', {
        x: 50,
        y: yPosition,
        size: 16,
        font: boldFont,
        color: rgb(0.1, 0.1, 0.1),
      });

      yPosition -= 25;

      const recommendations = [
        '- Consult with a mental health professional if needed',
        '- Practice self-care and stress management techniques',
        '- Maintain a regular sleep schedule',
        '- Engage in physical activity regularly',
        '- Stay connected with supportive friends and family',
      ];

      recommendations.forEach((rec) => {
        if (yPosition > 100) {
          page.drawText(rec, {
            x: 70,
            y: yPosition,
            size: 11,
            font,
            color: rgb(0.2, 0.2, 0.2),
          });
          yPosition -= 20;
        }
      });
    }

    // فوتر
    page.drawText('Generated by Testology - testology.com', {
      x: 50,
      y: 30,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    page.drawText(`Generated on: ${new Date().toLocaleDateString('en-US')}`, {
      x: width - 200,
      y: 30,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    // تولید PDF
    const pdfBytes = await pdfDoc.save();

    // ارسال PDF
    return new NextResponse(pdfBytes, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="testology-report-${testId}.pdf"`,
      },
    });

  } catch (error) {
    console.error('Error generating PDF:', error);
    return NextResponse.json(
      { error: 'Internal server error' }, 
      { status: 500 }
    );
  }
}

/**
 * تابع کمکی برای تقسیم متن به خطوط با طول مشخص
 */
function wrapText(text: string, maxLength: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let currentLine = '';

  words.forEach((word) => {
    if ((currentLine + word).length <= maxLength) {
      currentLine += (currentLine ? ' ' : '') + word;
    } else {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
    }
  });

  if (currentLine) lines.push(currentLine);
  return lines;
}
















